TOKEN='mytoken'


DATABASE_USER = "user"
DATABASE_PASSWORD = "12345"
DATABASE_HOST = "localhost"
DATABASE_NAME = "tvshows_db"

# POSTGRESQL_URL = f"postgresql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
MYSQL_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
